# Generated by Django 3.1.3 on 2021-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.CharField(max_length=31)),
                ('created_at', models.DateField(verbose_name='date created')),
                ('modified_at', models.DateField(verbose_name='modified_at')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'founded_date',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.CharField(max_length=31)),
                ('date_created', models.DateField(verbose_name='machine created on')),
                ('date_modified', models.DateField(verbose_name='machine modified on')),
                ('description', models.TextField()),
                ('manufacturers', models.ManyToManyField(to='machines.Manufacturer')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'founded_date',
            },
        ),
    ]
